### ISSUE TITLE
[BUG] in version [VERSION]

### ISSUE THREAD

**Issue by huwoujoli** [legoraft/simple-survival-tweaks#5]
**Description**
The functionality of the debug stick in survival is only partial. The right-click functionality is complete, however the left-click functionality doesn't work

**Comment by legoraft** [comment]
Debug stick can now cycle through items as of release [1.1.0](https://github.com/legoraft/simple-survival-tweaks/releases/tag/1.1.0-1.20.2). It uses shift and right click to cycle, because I couldn't make left click functionality working. Left click does work in creative tho
